
services:
  dana-main:
    build:
      context: .
      dockerfile: ./Dockerfile.main
    networks:
      - dana
    ports:
      - 8080:8080
    environment:
      - MODE=1
  dana-remote:
    build:
      context: .
      dockerfile: ./Dockerfile.wasm-worker
    ports:
      - 8081:8081
    environment:
      - PORT=8081
    networks:
      - dana
  dana-remote-2:
    build:
      context: .
      dockerfile: ./Dockerfile.wasm-worker
    ports:
      - 8082:8082
    environment:
      - PORT=8082
    networks:
      - dana
      - serial

networks:
  dana:
    driver: bridge
  serial:
    driver: bridge